# Generated by Django 3.1.2 on 2020-10-18 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.DecimalField(blank=True, decimal_places=15, help_text='Longitude Coordinate for Squirrel sighting point', max_digits=20, max_length=100)),
                ('Y', models.DecimalField(blank=True, decimal_places=15, help_text='Latitude Coordinate for Squirrel sighting point', max_digits=20, max_length=100)),
                ('UID', models.CharField(help_text='Identification tag for Squirrel sighting', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Squirrel sighting session morning or late afternoon', max_length=100)),
                ('Date', models.IntegerField(help_text='Session of sighting day and month')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Value is either adult or juvenile', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='fur color of squirrel', max_length=100)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='sighter instructed squirrel location', max_length=50)),
                ('Specific_Location', models.CharField(blank=True, help_text='sighter commentary on  squirrel location', max_length=200)),
                ('Running', models.BooleanField(default=False, help_text='Squirrel was seen running', max_length=10)),
                ('Chasing', models.BooleanField(default=False, help_text='Squirrel was seen chasing', max_length=10)),
                ('Climbing', models.BooleanField(default=False, help_text='Squirrel was seen climbing', max_length=10)),
                ('Eating', models.BooleanField(default=False, help_text='Squirrel was seen eating', max_length=10)),
                ('Foraging', models.BooleanField(default=False, help_text='Squirrel was seen foraging for food', max_length=10)),
                ('Other_activities', models.CharField(blank=True, help_text='no description available ', max_length=200)),
                ('Kuks', models.BooleanField(default=False, help_text='Squirrel was heard kukking, a chirpy vocal communication', max_length=10)),
                ('Quaas', models.BooleanField(default=False, help_text='Squirrel was heard quaaing, an elongated vocal communication', max_length=10)),
                ('Moans', models.BooleanField(default=False, help_text='Squirrel was heard moaning, a high-pitched vocal communication', max_length=10)),
                ('Tail_flags', models.BooleanField(default=False, help_text='Squirrel was seen flagging its tail', max_length=10)),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Squirrel was seen twitching its tail', max_length=10)),
                ('Approaches', models.BooleanField(default=False, help_text='Squirrel was seen approaching human, seeking food', max_length=10)),
                ('Indifferent', models.BooleanField(default=False, help_text='Squirrel was indifferent to human presence', max_length=10)),
                ('Runs_From', models.BooleanField(default=False, help_text='Squirrel was seen running from humans, seeing them as a threat', max_length=10)),
            ],
        ),
    ]
